import './globals.css'
import { Anybody } from 'next/font/google'

const any = Anybody({ subsets: ['latin'] })

export const metadata = {
  title: '🎥VidBG',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={any.className}>{children}</body>
    </html>
  )
}
